"""Adding alarms and notifications

Revision ID: 32d90f2f5eba
Revises: d550d68b4f17
Create Date: 2020-01-10 13:10:07.498504

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '32d90f2f5eba'
down_revision = 'd550d68b4f17'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('uuid', postgresql.UUID(as_uuid=True), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('msg', sa.String(length=128), nullable=True),
    sa.Column('severity', sa.String(length=16), nullable=True),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('uuid')
    )
    op.create_table('alarm_params',
    sa.Column('uuid', postgresql.UUID(as_uuid=True), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('ep_uuid', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('msg_on', sa.String(length=128), nullable=True),
    sa.Column('msg_off', sa.String(length=128), nullable=True),
    sa.Column('severity', sa.Enum('Info', 'Warning', 'Error', 'Critical', name='alarmseverityenum'), nullable=True),
    sa.Column('acl', sa.Integer(), nullable=True),
    sa.Column('triggered', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['ep_uuid'], ['endpoints.uuid'], ),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('uuid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('alarm_params')
    op.drop_table('notifications')
    # ### end Alembic commands ###
