"""Adding rooms

Revision ID: 5711fbce72de
Revises: 943401e3a6a9
Create Date: 2019-12-11 16:11:35.032816

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5711fbce72de'
down_revision = '943401e3a6a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rooms',
    sa.Column('uuid', postgresql.UUID(as_uuid=True), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('uuid')
    )
    op.create_table('device_room',
    sa.Column('uuid', postgresql.UUID(as_uuid=True), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('device_uuid', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('room_uuid', postgresql.UUID(as_uuid=True), nullable=True),
    sa.ForeignKeyConstraint(['device_uuid'], ['devices.uuid'], ),
    sa.ForeignKeyConstraint(['room_uuid'], ['rooms.uuid'], ),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('uuid')
    )
    op.create_unique_constraint(None, 'dev_params', ['uuid'])
    op.create_unique_constraint(None, 'dev_sources', ['uuid'])
    op.create_unique_constraint(None, 'devices', ['uuid'])
    op.create_unique_constraint(None, 'devices', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'devices', type_='unique')
    op.drop_constraint(None, 'devices', type_='unique')
    op.drop_constraint(None, 'dev_sources', type_='unique')
    op.drop_constraint(None, 'dev_params', type_='unique')
    op.drop_table('device_room')
    op.drop_table('rooms')
    # ### end Alembic commands ###
