"""Deleted keypairs on setpoints

Revision ID: 587fdcbb0e89
Revises: a7a3c88fd9fc
Create Date: 2019-12-12 19:18:24.265782

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '587fdcbb0e89'
down_revision = 'a7a3c88fd9fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('setpoint_pairs')
    op.add_column('setpoint_params', sa.Column('name', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('setpoint_params', 'name')
    op.create_table('setpoint_pairs',
    sa.Column('uuid', postgresql.UUID(), server_default=sa.text('uuid_generate_v4()'), autoincrement=False, nullable=False),
    sa.Column('params_uuid', postgresql.UUID(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('value', postgresql.BYTEA(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['params_uuid'], ['setpoint_params.uuid'], name='setpoint_pairs_params_uuid_fkey'),
    sa.PrimaryKeyConstraint('uuid', name='setpoint_pairs_pkey'),
    sa.UniqueConstraint('uuid', name='setpoint_pairs_uuid_key')
    )
    # ### end Alembic commands ###
