"""Initial

Revision ID: 5bd4104d9eef
Revises: 
Create Date: 2019-12-10 02:55:49.142648

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5bd4104d9eef'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('drivers',
    sa.Column('uuid', postgresql.UUID(as_uuid=True), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('driver_type', sa.Enum('mqtt', name='drivertypeenum'), nullable=True),
    sa.Column('comment', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('uuid')
    )
    op.create_table('mqtt_types',
    sa.Column('uuid', postgresql.UUID(as_uuid=True), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('read_template', sa.String(length=256), nullable=False),
    sa.Column('write_template', sa.String(length=256), nullable=True),
    sa.Column('comment', sa.String(length=64), nullable=True),
    sa.Column('parameters', postgresql.JSON(none_as_null=256, astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('uuid')
    )
    op.create_table('driver_parameters',
    sa.Column('uuid', postgresql.UUID(as_uuid=True), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('driver_uuid', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('param_name', sa.String(length=64), nullable=True),
    sa.Column('param_type', sa.String(length=64), nullable=True),
    sa.Column('param_value', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['driver_uuid'], ['drivers.uuid'], ),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('uuid')
    )
    op.create_table('endpoints',
    sa.Column('uuid', postgresql.UUID(as_uuid=True), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('driver_uuid', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('driver_type', sa.Enum('mqtt', name='drivertypeenum'), nullable=True),
    sa.ForeignKeyConstraint(['driver_uuid'], ['drivers.uuid'], ),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('uuid')
    )
    op.create_table('mqtt_params',
    sa.Column('uuid', postgresql.UUID(as_uuid=True), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('ep_uuid', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('type_uuid', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('topic_read', sa.String(length=128), nullable=False),
    sa.Column('topic_write', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['ep_uuid'], ['endpoints.uuid'], ),
    sa.ForeignKeyConstraint(['type_uuid'], ['mqtt_types.uuid'], ),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('uuid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mqtt_params')
    op.drop_table('endpoints')
    op.drop_table('driver_parameters')
    op.drop_table('mqtt_types')
    op.drop_table('drivers')
    # ### end Alembic commands ###
