"""Setpoint Driver

Revision ID: 790454c92907
Revises: fbad0d4dc5d2
Create Date: 2019-12-12 19:05:39.372425

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '790454c92907'
down_revision = 'fbad0d4dc5d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('setpoint_params',
    sa.Column('uuid', postgresql.UUID(as_uuid=True), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('ep_uuid', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('value', sa.Binary(), nullable=True),
    sa.ForeignKeyConstraint(['ep_uuid'], ['endpoints.uuid'], ),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('uuid')
    )
    op.create_table('setpoint_pairs',
    sa.Column('uuid', postgresql.UUID(as_uuid=True), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('params_uuid', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('value', sa.Binary(), nullable=True),
    sa.ForeignKeyConstraint(['params_uuid'], ['setpoint_params.uuid'], ),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('uuid')
    )
    op.create_unique_constraint(None, 'conditions', ['uuid'])
    op.create_unique_constraint(None, 'instruction_params', ['uuid'])
    op.create_unique_constraint(None, 'instructions', ['uuid'])

    op.execute("COMMIT")
    op.execute("ALTER TYPE drivertypeenum ADD VALUE 'setpoint'")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'instructions', type_='unique')
    op.drop_constraint(None, 'instruction_params', type_='unique')
    op.drop_constraint(None, 'conditions', type_='unique')
    op.drop_table('setpoint_pairs')
    op.drop_table('setpoint_params')
    # ### end Alembic commands ###
