"""Unique names on endpoints. Tokens

Revision ID: 821945a114ba
Revises: 5bd4104d9eef
Create Date: 2019-12-10 14:31:53.693539

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '821945a114ba'
down_revision = '5bd4104d9eef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('revoked_tokens',
    sa.Column('uuid', postgresql.UUID(as_uuid=True), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('jti', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('uuid')
    )
    op.create_unique_constraint(None, 'driver_parameters', ['uuid'])
    op.create_unique_constraint(None, 'drivers', ['uuid'])
    op.create_unique_constraint(None, 'endpoints', ['name'])
    op.create_unique_constraint(None, 'endpoints', ['uuid'])
    op.create_unique_constraint(None, 'mqtt_params', ['uuid'])
    op.create_unique_constraint(None, 'mqtt_types', ['uuid'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'mqtt_types', type_='unique')
    op.drop_constraint(None, 'mqtt_params', type_='unique')
    op.drop_constraint(None, 'endpoints', type_='unique')
    op.drop_constraint(None, 'endpoints', type_='unique')
    op.drop_constraint(None, 'drivers', type_='unique')
    op.drop_constraint(None, 'driver_parameters', type_='unique')
    op.drop_table('revoked_tokens')
    # ### end Alembic commands ###
