"""Fixing acl on notifications

Revision ID: 8abff26b6d5c
Revises: eab513c1e82c
Create Date: 2020-01-10 14:11:38.022987

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8abff26b6d5c'
down_revision = 'eab513c1e82c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('acl', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notifications', 'acl')
    # ### end Alembic commands ###
