"""Interface and preparing for client api

Revision ID: 8cfbe9d33c4c
Revises: 5711fbce72de
Create Date: 2019-12-11 17:46:57.167940

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8cfbe9d33c4c'
down_revision = '5711fbce72de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('uuid', postgresql.UUID(as_uuid=True), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('passhash', sa.Binary(), nullable=False),
    sa.Column('salt', sa.Binary(), nullable=False),
    sa.Column('acl', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('username'),
    sa.UniqueConstraint('uuid')
    )
    op.create_table('interfaces',
    sa.Column('uuid', postgresql.UUID(as_uuid=True), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('device_uuid', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('read_acl', sa.Integer(), nullable=True),
    sa.Column('write_acl', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['device_uuid'], ['devices.uuid'], ),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('device_uuid'),
    sa.UniqueConstraint('uuid')
    )
    op.create_unique_constraint(None, 'device_room', ['uuid'])
    op.create_unique_constraint(None, 'rooms', ['uuid'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'rooms', type_='unique')
    op.drop_constraint(None, 'device_room', type_='unique')
    op.drop_table('interfaces')
    op.drop_table('users')
    # ### end Alembic commands ###
