"""Fixing driver type enum

Revision ID: 9d0be62b91c1
Revises: 32d90f2f5eba
Create Date: 2020-01-10 13:10:28.140771

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d0be62b91c1'
down_revision = '32d90f2f5eba'
branch_labels = None
depends_on = None

name = 'drivertypeenum'
tmp_name = 'tmp_' + name

old_options = ('mqtt', 'setpoint',)
new_options = sorted(old_options + ('alarm',))

new_type = sa.Enum(*new_options, name=name)
old_type = sa.Enum(*old_options, name=name)

tcr1 = sa.sql.table('drivers',
                    sa.Column('driver_type', new_type, nullable=False))
tcr2 = sa.sql.table('endpoints',
                    sa.Column('driver_type', new_type, nullable=False))


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'alarm_params', ['uuid'])
    op.create_unique_constraint(None, 'notifications', ['uuid'])

    op.execute('ALTER TYPE ' + name + ' RENAME TO ' + tmp_name)

    new_type.create(op.get_bind())
    op.execute('ALTER TABLE drivers ALTER COLUMN driver_type ' +
               'TYPE ' + name + ' USING driver_type::text::' + name)
    op.execute('ALTER TABLE endpoints ALTER COLUMN driver_type ' +
               'TYPE ' + name + ' USING driver_type::text::' + name)
    op.execute('DROP TYPE ' + tmp_name)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'notifications', type_='unique')
    op.drop_constraint(None, 'alarm_params', type_='unique')

    op.execute(tcr1.update().where(tcr1.c.driver_type=='alarm')
               .values(driver_type=None))
    op.execute(tcr2.update().where(tcr2.c.driver_type=='alarm')
               .values(driver_type=None))

    op.execute('ALTER TYPE ' + name + ' RENAME TO ' + tmp_name)

    old_type.create(op.get_bind())
    op.execute('ALTER TABLE drivers ALTER COLUMN driver_type ' +
               'TYPE ' + name + ' USING driver_type::text::' + name)
    op.execute('ALTER TABLE endpoints ALTER COLUMN driver_type ' +
               'TYPE ' + name + ' USING driver_type::text::' + name)
    op.execute('DROP TYPE ' + tmp_name)
    # ### end Alembic commands ###
