"""deleted device parameters

Revision ID: 9e1b9307014e
Revises: 8cfbe9d33c4c
Create Date: 2019-12-12 15:42:27.323486

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9e1b9307014e'
down_revision = '8cfbe9d33c4c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dev_params')
    op.create_unique_constraint(None, 'interfaces', ['uuid'])
    op.create_unique_constraint(None, 'users', ['uuid'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'interfaces', type_='unique')
    op.create_table('dev_params',
    sa.Column('uuid', postgresql.UUID(), server_default=sa.text('uuid_generate_v4()'), autoincrement=False, nullable=False),
    sa.Column('device_uuid', postgresql.UUID(), autoincrement=False, nullable=True),
    sa.Column('device_param', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('value', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('value_type', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['device_uuid'], ['devices.uuid'], name='dev_params_device_uuid_fkey'),
    sa.PrimaryKeyConstraint('uuid', name='dev_params_pkey'),
    sa.UniqueConstraint('uuid', name='dev_params_uuid_key')
    )
    # ### end Alembic commands ###
