"""Setpoint Driver Enum

Revision ID: a7a3c88fd9fc
Revises: 790454c92907
Create Date: 2019-12-12 19:09:29.441467

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7a3c88fd9fc'
down_revision = '790454c92907'
branch_labels = None
depends_on = None


name = 'drivertypeenum'
tmp_name = 'tmp_' + name

old_options = ('mqtt',)
new_options = sorted(old_options + ('setpoint',))

new_type = sa.Enum(*new_options, name=name)
old_type = sa.Enum(*old_options, name=name)

tcr1 = sa.sql.table('drivers',
                    sa.Column('driver_type', new_type, nullable=False))
tcr2 = sa.sql.table('endpoints',
                    sa.Column('driver_type', new_type, nullable=False))


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'setpoint_pairs', ['uuid'])
    op.create_unique_constraint(None, 'setpoint_params', ['uuid'])

    op.execute('ALTER TYPE ' + name + ' RENAME TO ' + tmp_name)

    new_type.create(op.get_bind())
    op.execute('ALTER TABLE drivers ALTER COLUMN driver_type ' +
               'TYPE ' + name + ' USING driver_type::text::' + name)
    op.execute('ALTER TABLE endpoints ALTER COLUMN driver_type ' +
               'TYPE ' + name + ' USING driver_type::text::' + name)
    op.execute('DROP TYPE ' + tmp_name)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'setpoint_params', type_='unique')
    op.drop_constraint(None, 'setpoint_pairs', type_='unique')

    op.execute(tcr1.update().where(tcr1.c.driver_type=='setpoint')
               .values(driver_type=None))
    op.execute(tcr2.update().where(tcr2.c.driver_type=='setpoint')
               .values(driver_type=None))

    op.execute('ALTER TYPE ' + name + ' RENAME TO ' + tmp_name)

    old_type.create(op.get_bind())
    op.execute('ALTER TABLE drivers ALTER COLUMN driver_type ' +
               'TYPE ' + name + ' USING driver_type::text::' + name)
    op.execute('ALTER TABLE endpoints ALTER COLUMN driver_type ' +
               'TYPE ' + name + ' USING driver_type::text::' + name)
    op.execute('DROP TYPE ' + tmp_name)
    # ### end Alembic commands ###
