"""triggers, scenario

Revision ID: bca5d99fd0a2
Revises: 9e1b9307014e
Create Date: 2019-12-12 16:32:29.121216

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bca5d99fd0a2'
down_revision = '9e1b9307014e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
