"""Added storage device

Revision ID: d550d68b4f17
Revises: 587fdcbb0e89
Create Date: 2019-12-12 19:20:44.475399

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd550d68b4f17'
down_revision = '587fdcbb0e89'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("COMMIT")
    op.execute("ALTER TYPE deviceentenum ADD VALUE 'Storage'")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
