"""Removed incorrect name from alarms

Revision ID: eab513c1e82c
Revises: 9d0be62b91c1
Create Date: 2020-01-10 13:32:02.649832

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eab513c1e82c'
down_revision = '9d0be62b91c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('alarm_params', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alarm_params', sa.Column('name', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
