[default]
flask_secret_key='\xddi{\xd3Ba%\\\xb4C\xa1\x83\x06B\xcc\x01d\x116B\xaa\x9dB\xb6?i\x84f~\x86\xbeO'
jwt_secret_key='\xb5\xa9\x952\xb3\xd4O3H5XK:\t:?[\x97\xa9<\xa2\r9\xd5\x83\xed\xed\xf0\xac(\xae\xc4'

[development]
psql_user='shc_dev'
psql_pass='12344321'